"""perf_tracker.py — Performance Tracker untuk sinyal real IDX Alpha Screener v3
======================================================================
Log setiap sinyal BUY/WEAK_BUY → CSV + evaluasi mingguan.

Flow:
  1. record_signal() → simpan entry (tanggal, ticker, harga, skor, regime, tier)
  2. record_exit()   → update exit (tanggal, harga, return, exit_reason)
  3. weekly_report() → hitung WR, avg return, drawdown, profit/loss

File CSV lokasi:
  {SCREENER_DIR}/data/perf_tracker.csv
"""

import os
import csv
import logging
from datetime import datetime, date, timedelta
from typing import Optional
import numpy as np

logger = logging.getLogger("perf_tracker")

# ── Default paths ──
DEFAULT_DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
DEFAULT_CSV = os.path.join(DEFAULT_DATA_DIR, "perf_tracker.csv")
WEEKLY_REPORT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output")

# ── CSV Fieldnames ──
FIELDS = [
    "signal_id",       # Unique ID: YYYYMMDD_TICKER
    "ticker",          # BBCA, ADMR, etc.
    "signal",          # BUY, WEAK_BUY
    "score",           # Skor v3 (0-100)
    "regime",          # BULL/BEAR/RANGING/HIGH_VOLATILITY
    "slippage_tier",   # LARGE/MID/SMALL/MICRO
    "total_cost_pct",  # Round-trip cost (slippage + fee)
    "entry_date",      # YYYY-MM-DD
    "entry_price",     # Harga masuk
    "exit_date",       # YYYY-MM-DD (NONE jika masih open)
    "exit_price",      # Harga keluar (NONE jika masih open)
    "exit_reason",     # STANDARD / HARD_STOP / FLAT_EXIT / MAX_HOLD / MANUAL
    "return_pct",      # Return after cost (NONE jika masih open)
    "is_closed",       # True/False
    "notes",           # Optional
]


class PerformanceTracker:
    """Track performance of every signal generated by the screener."""

    def __init__(self, csv_path: str = None):
        self.csv_path = csv_path or DEFAULT_CSV
        os.makedirs(os.path.dirname(self.csv_path), exist_ok=True)
        self._ensure_header()
        self._cache = []  # In-memory cache of open positions
        self._load_open_positions()

    def _ensure_header(self):
        """Create CSV with header if not exists."""
        if not os.path.exists(self.csv_path):
            with open(self.csv_path, "w", newline="") as f:
                writer = csv.DictWriter(f, fieldnames=FIELDS)
                writer.writeheader()
            logger.info("Perf tracker CSV created: %s", self.csv_path)

    def _load_open_positions(self):
        """Load all open (not closed) positions into cache."""
        self._cache = []
        if not os.path.exists(self.csv_path):
            return
        try:
            with open(self.csv_path) as f:
                reader = csv.DictReader(f)
                for row in reader:
                    if row.get("is_closed", "").strip().lower() != "true":
                        self._cache.append(row)
        except Exception as e:
            logger.warning("Gagal load perf tracker: %s", e)

    def _generate_id(self, ticker: str, entry_date: str) -> str:
        return f"{entry_date.replace('-', '')}_{ticker.upper()}"

    def record_signal(self, ticker: str, signal: str, score: float,
                      regime: str, slippage_tier: str, total_cost_pct: float,
                      entry_price: float, entry_date=None, notes=""):
        """
        Catat sinyal baru (BUY/WEAK_BUY) ke tracker.

        Parameters
        ----------
        ticker : str — BBCA.JK or BBCA
        signal : str — BUY or WEAK_BUY
        score : float — skor v3
        regime : str — BULL/BEAR/RANGING/HIGH_VOLATILITY
        slippage_tier : str — LARGE/MID/SMALL/MICRO
        total_cost_pct : float — round-trip cost %
        entry_price : float — harga masuk
        entry_date : str or None — YYYY-MM-DD, default today
        notes : str — optional
        """
        if signal not in ("STRONG_BUY", "BUY", "WEAK_BUY"):
            return  # Only track buy signals

        clean_ticker = ticker.replace(".JK", "").upper()
        entry_date = entry_date or date.today().isoformat()
        signal_id = self._generate_id(clean_ticker, entry_date)

        # Check duplicate
        for pos in self._cache:
            if pos["signal_id"] == signal_id:
                logger.debug("Duplicate signal: %s", signal_id)
                return

        row = {
            "signal_id": signal_id,
            "ticker": clean_ticker,
            "signal": "BUY" if signal == "STRONG_BUY" else signal,
            "score": f"{score:.1f}",
            "regime": regime,
            "slippage_tier": slippage_tier,
            "total_cost_pct": f"{total_cost_pct:.3f}",
            "entry_date": entry_date,
            "entry_price": f"{entry_price:.0f}",
            "exit_date": "",
            "exit_price": "",
            "exit_reason": "",
            "return_pct": "",
            "is_closed": "False",
            "notes": notes,
        }

        with open(self.csv_path, "a", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=FIELDS)
            writer.writerow(row)

        self._cache.append(row)
        logger.info("📝 Signal tracked: %s %s @ %.0f (score=%.1f, tier=%s, cost=%.2f%%)",
                    clean_ticker, signal, entry_price, score, slippage_tier, total_cost_pct)

    def record_exit(self, signal_id: str, exit_price: float,
                    exit_reason: str = "MANUAL", exit_date=None):
        """
        Catat exit (keluar dari posisi).

        Parameters
        ----------
        signal_id : str — dari record_signal (format: YYYYMMDD_TICKER)
        exit_price : float — harga keluar
        exit_reason : str — STANDARD/HARD_STOP/FLAT_EXIT/MAX_HOLD/MANUAL
        exit_date : str or None — YYYY-MM-DD
        """
        exit_date = exit_date or date.today().isoformat()

        # Read all rows, update the matching one
        rows = []
        updated = False
        with open(self.csv_path) as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row["signal_id"] == signal_id and row["is_closed"].strip().lower() != "true":
                    entry_price = float(row["entry_price"])
                    ret_pct = (exit_price - entry_price) / entry_price * 100
                    total_cost = float(row.get("total_cost_pct", 0.75))
                    ret_after_cost = ret_pct - total_cost

                    row["exit_date"] = exit_date
                    row["exit_price"] = f"{exit_price:.0f}"
                    row["exit_reason"] = exit_reason
                    row["return_pct"] = f"{ret_after_cost:.2f}"
                    row["is_closed"] = "True"
                    updated = True

                    logger.info("📊 Exit: %s @ %.0f (%s) — return=%.2f%% after cost",
                                signal_id, exit_price, exit_reason, ret_after_cost)
                rows.append(row)

        if not updated:
            logger.warning("⚠️  Signal not found or already closed: %s", signal_id)
            return

        with open(self.csv_path, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=FIELDS)
            writer.writeheader()
            writer.writerows(rows)

        # Refresh cache
        self._load_open_positions()

    def get_open_positions(self) -> list:
        """Daftar posisi yang masih terbuka."""
        return self._cache

    def get_all_signals(self) -> list:
        """Semua sinyal yang pernah direkam."""
        if not os.path.exists(self.csv_path):
            return []
        with open(self.csv_path) as f:
            return list(csv.DictReader(f))

    def weekly_report(self, report_date=None) -> Optional[dict]:
        """
        Generate laporan mingguan performance.

        Returns dict:
        {period, total_signals, closed_signals, open_signals,
         wr, avg_return, best_ticker, worst_ticker,
         win_loss_ratio, total_profit_loss_pct, avg_hold_days}
        """
        all_signals = self.get_all_signals()
        if not all_signals:
            logger.info("Belum ada sinyal untuk weekly report")
            return None

        report_date = report_date or date.today()
        # Calculate week range (last 7 days + previous 7 days = 14 day window)
        week_ago = report_date - timedelta(days=14)

        # Filter signals in this window
        week_signals = []
        for s in all_signals:
            if s.get("entry_date", ""):
                try:
                    d = datetime.strptime(str(s["entry_date"]).strip()[:10], "%Y-%m-%d").date()
                    if d >= week_ago:
                        week_signals.append(s)
                except (ValueError, TypeError):
                    continue

        if not week_signals:
            # Fallback: pakai semua signal
            week_signals = all_signals

        closed = [s for s in week_signals if s.get("is_closed", "").strip().lower() == "true"]
        open_pos = [s for s in week_signals if s.get("is_closed", "").strip().lower() != "true"]

        if not closed:
            logger.info("Weekly report: %d sinyal (%d open, 0 closed)",
                        len(week_signals), len(open_pos))
            return {
                "period": f"{week_ago} — {report_date}",
                "total_signals": len(week_signals),
                "closed_signals": 0,
                "open_signals": len(open_pos),
                "wr": 0.0,
                "avg_return": 0.0,
                "win_loss_ratio": 0.0,
                "total_profit_loss_pct": 0.0,
                "avg_hold_days": 0.0,
                "best_ticker": "",
                "worst_ticker": "",
            }

        returns = []
        hold_days = []
        ticker_returns = {}
        for s in closed:
            try:
                ret = float(s.get("return_pct", 0))
                returns.append(ret)

                ticker = s.get("ticker", "?")
                ticker_returns[ticker] = ticker_returns.get(ticker, []) + [ret]

                if s.get("entry_date") and s.get("exit_date"):
                    ed = datetime.strptime(str(s["entry_date"]).strip()[:10], "%Y-%m-%d").date()
                    xd = datetime.strptime(str(s["exit_date"]).strip()[:10], "%Y-%m-%d").date()
                    hold_days.append((xd - ed).days)
            except (ValueError, TypeError, ZeroDivisionError):
                continue

        if not returns:
            return None

        n_win = sum(1 for r in returns if r > 0)
        n_loss = sum(1 for r in returns if r < 0)
        wr = n_win / len(returns) * 100
        avg_ret = float(np.mean(returns)) if returns else 0.0
        total_pnl = sum(returns)

        # Best/worst ticker
        avg_per_ticker = {t: float(np.mean(r)) for t, r in ticker_returns.items()}
        best = max(avg_per_ticker, key=avg_per_ticker.get) if avg_per_ticker else ""
        worst = min(avg_per_ticker, key=avg_per_ticker.get) if avg_per_ticker else ""

        avg_hold = float(np.mean(hold_days)) if hold_days else 0.0

        report = {
            "period": f"{week_ago.isoformat()} — {report_date.isoformat()}",
            "total_signals": len(week_signals),
            "closed_signals": len(closed),
            "open_signals": len(open_pos),
            "wr": round(wr, 1),
            "avg_return": round(avg_ret, 2),
            "win_loss_ratio": round(n_win / n_loss, 2) if n_loss > 0 else float("inf"),
            "total_profit_loss_pct": round(total_pnl, 2),
            "avg_hold_days": round(avg_hold, 1),
            "best_ticker": best,
            "worst_ticker": worst,
        }

        # Print report
        print(f"\n{'='*60}")
        print(f"  📊 PERFORMANCE REPORT — {report_date}")
        print(f"  Periode: {report['period']}")
        print(f"{'='*60}")
        print(f"  Total sinyal:   {report['total_signals']}")
        print(f"  Closed:         {report['closed_signals']}")
        print(f"  Open:           {report['open_signals']}")
        print(f"  ─────────────────────────────")
        print(f"  Win Rate:       {report['wr']:.1f}%")
        print(f"  Avg Return:     {report['avg_return']:+.2f}%")
        print(f"  Win/Loss Ratio: {report['win_loss_ratio']}")
        print(f"  Total P&L:      {report['total_profit_loss_pct']:+.2f}%")
        print(f"  Avg Hold:       {report['avg_hold_days']:.1f} hari")
        print(f"  Best Ticker:    {report['best_ticker']}")
        print(f"  Worst Ticker:   {report['worst_ticker']}")
        print(f"{'='*60}\n")

        # Save report to CSV
        os.makedirs(WEEKLY_REPORT_DIR, exist_ok=True)
        report_path = os.path.join(WEEKLY_REPORT_DIR, f"perf_weekly_{report_date.isoformat()}.csv")
        with open(report_path, "w", newline="") as f:
            writer = csv.writer(f)
            for k, v in report.items():
                writer.writerow([k, v])
        logger.info("Weekly report saved: %s", report_path)

        return report

    def close_expired_positions(self, current_prices: dict,
                                config: dict = None):
        """
        Otomatis close posisi yang kena exit strategy (hard stop, max hold, flat).
        Dipanggil oleh cron / manual.

        Parameters
        ----------
        current_prices : dict — {ticker: price}
        config : dict — {max_hold_days, flat_exit_days, flat_exit_threshold_pct, hard_stop_pct}
        """
        cfg = config or {
            "max_hold_days": 15,
            "flat_exit_days": 7,
            "flat_exit_threshold_pct": 2.0,
            "hard_stop_pct": -15.0,
        }
        today = date.today()
        closed_count = 0

        for pos in self._cache:
            ticker = pos["ticker"]
            if ticker not in current_prices:
                continue

            current_price = current_prices[ticker]
            entry_price = float(pos["entry_price"])
            entry_date = datetime.strptime(str(pos["entry_date"]).strip()[:10], "%Y-%m-%d").date()
            hold_days = (today - entry_date).days
            ret_pct = (current_price - entry_price) / entry_price * 100

            # Hard stop check
            if ret_pct <= cfg["hard_stop_pct"]:
                self.record_exit(pos["signal_id"], current_price, "HARD_STOP", today.isoformat())
                closed_count += 1
                continue

            # Max hold check
            if hold_days >= cfg["max_hold_days"]:
                self.record_exit(pos["signal_id"], current_price, "MAX_HOLD", today.isoformat())
                closed_count += 1
                continue

            # Flat exit check
            if hold_days >= cfg["flat_exit_days"] and abs(ret_pct) < cfg["flat_exit_threshold_pct"]:
                self.record_exit(pos["signal_id"], current_price, "FLAT_EXIT", today.isoformat())
                closed_count += 1
                continue

        if closed_count > 0:
            logger.info("Auto-closed %d positions via exit strategy", closed_count)

        return closed_count
